### ISSUE TITLE
Too many open files (os error 24) on macOS

### ISSUE THREAD

**Issue by nathany** [lycheeverse/lychee#1248]
When running `lychee README.md` against this repository https://github.com/dariubs/GoBooks, I am seeing the following error on macOS 13.5.1, however these links are considered fine by GitHub Actions with Ubuntu.

```
✗ [ERR] https://github.com/thewhitetulip/web-dev-golang-anti-textbook | Failed: Network error: dns error: proto error: io error: Too many open files (os error 24)
```

It's happening on quite a few links.

Running against commit 1c71e7329e369b510afb806f484aa4e415b9aeb2 of https://github.com/dariubs/GoBooks with lychee installed via Homebrew.

> ❯ lychee --version
> lychee 0.13.0

**Comment by nathany** [comment]
Apologies, I didn't see an issue for it, but it's addressed in the README.

commit f2109a41a7b0ab404845d105729dc8a434b61f1c

Still, kind've wonder if the default max concurrency should be lower, at least on macOS, to avoid this out-of-the-box issue.

**Comment by mre** [comment]
Yeah, we should fix that. I will look at the repo to see what I can do.

**Comment by mre** [comment]
Similar discussion: https://github.com/RustScan/RustScan/issues/25

**Comment by nathany** [comment]
@mre Thanks. It is still occurring on main with that repo, with ~148 links to check. 

Setting `--max-concurrency 32` resolves it on macOS.

**Comment by mre** [comment]
* [ ] Try to use `rlimit` crate to detect resource limits and limit the number open files to that.

**Comment by reagle** [comment]
I just encountered this on:

| lychee 0.14.3
| macOS 14.3.1 23D60 arm64

**Comment by mre** [comment]
I think `rlimit` is the way to go to fix this once and for all (famous last words).
In the meantime, your best bet is `--max-concurrency`, unfortunately.

**Comment by mre** [comment]
We recently switched to `ignore` in #1500 thanks to @thomas-zahner. I just tried triggering this bug again and so far haven't managed to. Tried the [dariubs/GoBooks](https://github.com/dariubs/GoBooks) repo and a few others. It's fast and stable. 🤞 

@nathany, @reagle, if you have time to try again and report back, that would be awesome. Closing as fixed. We can reopen the issue if someone finds a way to reproduce it.

**Comment by ngoldbaum** [comment]
FWIW I'm seeing this building the pyo3 docs on an M3 Macbook Pro.

**Comment by mre** [comment]
Hey there @ngoldbaum,

which lychee version do you use? 
Can you show the commands you executed?

**Comment by ngoldbaum** [comment]
@mre this is with lychee 0.18.1 installed via homebrew:

```
goldbaum at Nathans-MBP in ~
○  ulimit -n
256

goldbaum at Nathans-MBP in ~
○  cd Documents/pyo3

goldbaum at Nathans-MBP in ~/Documents/pyo3 on fix-docs-deploy
± nox -s check-guide
nox > Running session check-guide
nox > mdbook build -d /Users/goldbaum/Documents/pyo3/target/guide guide
2025-03-11 13:35:08 [INFO] (mdbook::book): Book building has started
2025-03-11 13:35:08 [WARN] (mdbook::preprocess::cmd): The command wasn't found, is the "tabs" preprocessor installed?
2025-03-11 13:35:08 [WARN] (mdbook::preprocess::cmd): 	Command: mdbook-tabs
2025-03-11 13:35:08 [INFO] (mdbook::book): Running the html backend
nox > cargo doc --lib --no-default-features --features=full,jiff-02 --no-deps --workspace --exclude=pyo3-macros --exclude=pyo3-macros-backend
    Updating crates.io index
     Locking 138 packages to latest compatible versions
  Downloaded anyhow v1.0.97
  Downloaded ppv-lite86 v0.2.21
  Downloaded either v1.15.0
  Downloaded once_cell v1.21.0
  Downloaded trybuild v1.0.104
  Downloaded tempfile v3.18.0
  Downloaded ryu v1.0.20
  Downloaded serde_derive v1.0.219
  Downloaded serde v1.0.219
  Downloaded jiff-static v0.2.4
  Downloaded indexmap v2.8.0
  Downloaded uuid v1.15.1
  Downloaded serde_json v1.0.140
  Downloaded chrono v0.4.40
  Downloaded zerocopy v0.8.23
  Downloaded rustix v1.0.2
  Downloaded jiff v0.2.4
  Downloaded libc v0.2.171
  Downloaded 18 crates (3.1 MB) in 0.43s
   Compiling target-lexicon v0.13.2
   Compiling autocfg v1.4.0
   Compiling once_cell v1.21.0
   Compiling proc-macro2 v1.0.94
   Compiling regex-syntax v0.8.5
   Compiling unicode-ident v1.0.18
   Compiling rand_core v0.6.4
   Compiling siphasher v1.0.1
   Compiling libc v0.2.171
    Checking core-foundation-sys v0.8.7
   Compiling getrandom v0.3.1
   Compiling phf_shared v0.11.3
   Compiling rand v0.8.5
    Checking iana-time-zone v0.1.61
   Compiling anyhow v1.0.97
    Checking foldhash v0.1.4
    Checking equivalent v1.0.2
   Compiling serde v1.0.219
    Checking allocator-api2 v0.2.21
   Compiling num-traits v0.2.19
   Compiling memoffset v0.9.1
   Compiling phf_generator v0.11.3
   Compiling rust_decimal v1.36.0
   Compiling phf_codegen v0.11.3
   Compiling eyre v0.6.12
   Compiling regex-automata v0.4.9
    Checking cfg-if v1.0.0
   Compiling heck v0.5.0
   Compiling quote v1.0.39
   Compiling syn v2.0.100
    Checking num-integer v0.1.46
    Checking chrono v0.4.40
   Compiling regex v1.11.1
   Compiling pyo3-build-config v0.24.0 (/Users/goldbaum/Documents/pyo3/pyo3-build-config)
    Checking num-bigint v0.4.6
    Checking hashbrown v0.15.2
   Compiling parse-zoneinfo v0.3.1
    Checking phf v0.11.3
    Checking indenter v0.3.3
    Checking arrayvec v0.7.6
   Compiling chrono-tz-build v0.4.0
    Checking indexmap v2.8.0
    Checking uuid v1.15.1
    Checking num-complex v0.4.6
    Checking smallvec v1.14.0
    Checking num-rational v0.4.2
    Checking either v1.15.0
    Checking jiff v0.2.4
   Compiling indoc v2.0.6
    Checking unindent v0.2.4
   Compiling chrono-tz v0.10.1
 Documenting pyo3-build-config v0.24.0 (/Users/goldbaum/Documents/pyo3/pyo3-build-config)
   Compiling serde_derive v1.0.219
   Compiling pyo3-ffi v0.24.0 (/Users/goldbaum/Documents/pyo3/pyo3-ffi)
   Compiling pyo3-macros-backend v0.24.0 (/Users/goldbaum/Documents/pyo3/pyo3-macros-backend)
   Compiling pyo3 v0.24.0 (/Users/goldbaum/Documents/pyo3)
   Compiling pyo3-pytests v0.1.0 (/Users/goldbaum/Documents/pyo3/pytests)
 Documenting pyo3-ffi v0.24.0 (/Users/goldbaum/Documents/pyo3/pyo3-ffi)
   Compiling pyo3-macros v0.24.0 (/Users/goldbaum/Documents/pyo3/pyo3-macros)
 Documenting pyo3 v0.24.0 (/Users/goldbaum/Documents/pyo3)
 Documenting pyo3-pytests v0.1.0 (/Users/goldbaum/Documents/pyo3/pytests)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 8.77s
   Generated /Users/goldbaum/Documents/pyo3/target/doc/pyo3/index.html and 3 other files
nox > lychee --include-fragments /Users/goldbaum/Documents/pyo3/guide/src --remap 'file:///Users/goldbaum/Documents/pyo3/guide/src/([^/]*/)*?%7B%7B#PYO3_DOCS_URL}} file:///Users/goldbaum/Documents/pyo3/target/doc' --remap 'https://pyo3.rs/v0.24.0 file:///Users/goldbaum/Documents/pyo3/target/guide' --remap 'https://pyo3.rs/main/ file:///Users/goldbaum/Documents/pyo3/target/guide/' --remap 'https://pyo3.rs/latest/ file:///Users/goldbaum/Documents/pyo3/target/guide/' --remap '%7B%7B#PYO3_DOCS_VERSION}} latest'
  411/411 ━━━━━━━━━━━━━━━━━━━━ Finished extracting links                        🔍 411 Total (in 3s) ✅ 411 OK 🚫 0 Errors
nox > lychee /Users/goldbaum/Documents/pyo3/target/doc --remap 'file:///Users/goldbaum/Documents/pyo3/guide/src/([^/]*/)*?%7B%7B#PYO3_DOCS_URL}} file:///Users/goldbaum/Documents/pyo3/target/doc' --remap 'https://pyo3.rs/v0.24.0 file:///Users/goldbaum/Documents/pyo3/target/guide' --remap 'https://pyo3.rs/main/ file:///Users/goldbaum/Documents/pyo3/target/guide/' --remap 'https://pyo3.rs/latest/ file:///Users/goldbaum/Documents/pyo3/target/guide/' --remap '%7B%7B#PYO3_DOCS_VERSION}} latest' --exclude=file:///Users/goldbaum/Documents/pyo3/target/doc --exclude=http://www.adobe.com/
Error: Cannot read input content from file `/Users/goldbaum/Documents/pyo3/target/doc/pyo3/types/struct.PyGenericAlias.html`

Caused by:
    Too many open files (os error 24)
nox > Command lychee /Users/goldbaum/Documents/pyo3/target/doc --remap 'file:///Users/goldbaum/Documents/pyo3/guide/src/([^/]*/)*?%7B%7B#PYO3_DOCS_URL}} file:///Users/goldbaum/Documents/pyo3/target/doc' --remap 'https://pyo3.rs/v0.24.0 file:///Users/goldbaum/Documents/pyo3/target/guide' --remap 'https://pyo3.rs/main/ file:///Users/goldbaum/Documents/pyo3/target/guide/' --remap 'https://pyo3.rs/latest/ file:///Users/goldbaum/Documents/pyo3/target/guide/' --remap '%7B%7B#PYO3_DOCS_VERSION}} latest' --exclude=file:///Users/goldbaum/Documents/pyo3/target/doc --exclude=http://www.adobe.com/ failed with exit code 1
nox > Session check-guide failed.
```

**Comment by mre** [comment]
Tried to reproduce, but couldn't.

```sh
> ulimit -n 256
> cd /tmp
> git clone git@github.com:PyO3/pyo3.git
> cd pyo3
> cargo install mdbook-tabs
> mdbook build guide
> cargo doc --lib --no-default-features --features=full,jiff-02 --no-deps --workspace --exclude=pyo3-macros --exclude=pyo3-macros-backend
> lychee --include-fragments guide/src --remap 'file:///tmp/pyo3/guide/src/([^/]*/)*?%7B%7B#PYO3_DOCS_URL}} file:///tmp/pyo3/target/doc' --remap 'https://pyo3.rs/v0.24.0 file:///tmp/pyo3/target/guide' --remap 'https://pyo3.rs/main/ file:///tmp/pyo3/target/guide/' --remap 'https://pyo3.rs/latest/ file:///tmp/pyo3/target/guide/' --remap '%7B%7B#PYO3_DOCS_VERSION}} latest'
```

Works as expected, i.e. it doesn't print the error message you get. 🤔 Wonder if someone else could try?

**Comment by ngoldbaum** [comment]
Can you try doing e.g. `pip install nox` and then `nox -s check-guide`? Maybe it has something to do with lychee being run as a Python subprocess?

**Comment by mre** [comment]
Will do.

**Comment by mre** [comment]
Just tried; same result. It works for me. Very strange.

**Comment by mre** [comment]
It's hard to troubleshoot remotely, but here are a few more thoughts:

* While lychee is running, use `lsof -n -p $(pgrep lychee) | awk 'NR>1 {print}'` in a second terminal window to see exactly which files are open. Run it with e.g. `watch -n 0.1` to get some continous output. This is really just a poor man's debugger. `dtruss` is probably more sophisticated, but it's a bit harder to use and I couldn't get it to show the list of open files.

* You're probably hitting macOS file descriptor limits on your machine. This is a common issue, especially on macOS which has lower default limits than Linux. I hope I'm mistaken, but it might even be 256 file handles by default. See [here](https://developer.apple.com/forums/thread/735798). (Can someone clarify?)

* Can you try to increase the number of file handles [like this](https://stackoverflow.com/questions/42738899/setting-maxfile-on-os-x-macos-programmatically)?

* Using `--max-concurrency=32` (you can play with that number) will help, but lychee still needs a minimum of ~20 file handles for basic operations. These are used for:
  - Standard file descriptors (stdin, stdout, stderr)
  - Socket connections (HTTP requests)
  - SSL/TLS libraries (e.g. openssl)
  - System sockets for DNS resolution
  - Temporary files and KQueue handles
  - The files being checked

This explains why even with a lower concurrency setting, you might still hit the limit if your system's `ulimit -n` is set very low.

**Comment by mre** [comment]
I will close this once more to keep the issue tracker clean (well, actionable, mostly).
That said, I'd still be interested in the resolution for your case, @ngoldbaum. If you get around to testing it, please post a follow-up comment. From what I can see, this issue is highly environment-specific. macOS in particular does not have favorable defaults for this level of concurrency.

We use the `ignore` for file traversial, so the same problem might occur with ripgrep. 

Apart from the tips above, I'm out of my depth here, so if anyone ran into the same issue and found a workaround, feel free to share here. We can also add it to the [docs](https://lychee.cli.rs/troubleshooting/open-files/).

**Comment by ngoldbaum** [comment]
I’m on vacation this week and am planning to take a look at your suggestions next week.

**Comment by mre** [comment]
No rush. 💃

**Comment by ngoldbaum** [comment]
Sorry if I wasn't clear, increasing the number of allowed file handles does work, as does setting `--max-concurrency=32` (albeit lychee runs a lot more slowly), and the number of allowed file handles is the MacOS default, 256:

```
goldbaum at Nathans-MBP in ~/Documents/cryptography on pad-unpad-thread-safety
± ulimit -n
256
```

I just played around with `lsof`. Here's a spot where it looks like lychee is opening too many TCP connections:

```
lychee  5619 goldbaum  cwd       DIR               1,18     1312            45858143 /Users/goldbaum/Documents/pyo3
lychee  5619 goldbaum  txt       REG               1,18 23302336           116220633 /opt/homebrew/Cellar/lychee/0.18.1/bin/lychee
lychee  5619 goldbaum  txt       REG               1,18    65248           117017791 /Library/Preferences/Logging/.plist-cache.pP71pR2D
lychee  5619 goldbaum  txt       REG               1,18   854944           111000613 /opt/homebrew/Cellar/openssl@3/3.4.1/lib/libssl.3.dylib
lychee  5619 goldbaum  txt       REG               1,18  2423888 1152921500312498623 /usr/lib/dyld
lychee  5619 goldbaum  txt       REG               1,18  4305168           111000612 /opt/homebrew/Cellar/openssl@3/3.4.1/lib/libcrypto.3.dylib
lychee  5619 goldbaum  txt       REG               1,18   153355           117070552 /private/var/db/analyticsd/events.allowlist
lychee  5619 goldbaum  txt       REG               1,18   233968           113091266 /private/var/db/timezone/tz/2025a.1.0/icutz/icutz44l.dat
lychee  5619 goldbaum  txt       REG               1,18 32904864 1152921500312508906 /usr/share/icu/icudt74l.dat
lychee  5619 goldbaum    0u      CHR               16,7 0t306696                 731 /dev/ttys007
lychee  5619 goldbaum    1u      CHR               16,7 0t306696                 731 /dev/ttys007
lychee  5619 goldbaum    2u      CHR               16,7 0t306696                 731 /dev/ttys007
lychee  5619 goldbaum    3u   KQUEUE                                                 count=0, state=0xa
lychee  5619 goldbaum    4u   KQUEUE                                                 count=0, state=0xa
lychee  5619 goldbaum    5u   KQUEUE                                                 count=0, state=0xa
lychee  5619 goldbaum    6u     unix 0x5364f5401fa3f70a      0t0                     ->0x1db949ea6f8a853a
lychee  5619 goldbaum    7u     unix 0x1db949ea6f8a853a      0t0                     ->0x5364f5401fa3f70a
lychee  5619 goldbaum    8u     unix 0x5364f5401fa3f70a      0t0                     ->0x1db949ea6f8a853a
lychee  5619 goldbaum    9r      DIR               1,18      544           117340965 /Users/goldbaum/Documents/pyo3/target/doc
lychee  5619 goldbaum   10u     IPv4 0xa139e8b9bd6e4a76      0t0                 TCP 192.168.0.19:57689->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   11u     IPv4 0x469d621bd22274dd      0t0                 TCP 192.168.0.19:57646->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   12u     IPv4 0x65260e13bd51ac26      0t0                 TCP 192.168.0.19:57586->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   13u     unix 0xf11c556c98812b2e      0t0                     ->0x8be5ab5936bb2497
lychee  5619 goldbaum   14u     IPv4  0x5d4481017af156d      0t0                 TCP 192.168.0.19:57654->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   15u   KQUEUE                                                 count=0, state=0x8
lychee  5619 goldbaum   16u     IPv4 0xae8ce60809f07ca4      0t0                 TCP 192.168.0.19:57664->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   17u     IPv4 0x352eb7416db676c3      0t0                 TCP 192.168.0.19:57741->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   18u     IPv4 0xe946a51fc6d84c23      0t0                 TCP 192.168.0.19:57744->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   19r      DIR               1,18     2656           117344887 /Users/goldbaum/Documents/pyo3/target/doc/pyo3
lychee  5619 goldbaum   20u     IPv4 0x8c7011b4fe3ad290      0t0                 TCP 192.168.0.19:57765->75.2.60.5:https (ESTABLISHED)
lychee  5619 goldbaum   21u     IPv4 0x55f4ee8d72c7eaa7      0t0                 TCP 192.168.0.19:57732->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   22u     IPv4 0x6ee754ce1a4d20ab      0t0                 TCP 192.168.0.19:57751->151.101.0.223:https (ESTABLISHED)
lychee  5619 goldbaum   23u     IPv4 0x25e2c69350d809c7      0t0                 TCP 192.168.0.19:57813->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum   24u     IPv4 0xede6362831355094      0t0                 TCP 192.168.0.19:57704->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   25u     IPv4 0xe2d46728b20509ed      0t0                 TCP 192.168.0.19:57659->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   26u     IPv4 0xa1bdaeb05f0b9bfc      0t0                 TCP 192.168.0.19:57715->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   27u     IPv4 0xa1cf6190f7d3eb61      0t0                 TCP 192.168.0.19:57754->151.101.0.223:https (SYN_SENT)
lychee  5619 goldbaum   28u     IPv4 0x156e9a6d821f9aca      0t0                 TCP 192.168.0.19:57764->104.22.10.254:http (ESTABLISHED)
lychee  5619 goldbaum   29u     IPv4 0x78aa786aee532e0c      0t0                 TCP 192.168.0.19:57742->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   30u     IPv4 0x1bc869c3336091ba      0t0                 TCP 192.168.0.19:57840->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum   31u     IPv4 0xc97d1d9556d3598b      0t0                 TCP 192.168.0.19:57655->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   32u     IPv4 0x196c2017dec926c4      0t0                 TCP 192.168.0.19:57752->140.82.113.4:https (ESTABLISHED)
lychee  5619 goldbaum   33u     IPv4 0xcbcece9276035994      0t0                 TCP 192.168.0.19:57735->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   34u     IPv4 0xe8a8e43a13b1a0ad      0t0                 TCP 192.168.0.19:57653->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   35u     IPv4 0xfefaa5fcce12784d      0t0                 TCP 192.168.0.19:57797->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   36   NPOLICY
lychee  5619 goldbaum   37u     IPv4 0xb5a4cbe331190132      0t0                 TCP 192.168.0.19:57747->18.154.101.73:https (SYN_SENT)
lychee  5619 goldbaum   38u     IPv4  0x58b13a9ae58b047      0t0                 TCP 192.168.0.19:57616->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   39u     IPv4 0x109fdab44422d9dc      0t0                 TCP 192.168.0.19:57760->151.101.0.223:https (ESTABLISHED)
lychee  5619 goldbaum   40u     IPv4 0xffdce8384a618642      0t0                 TCP 192.168.0.19:57748->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   41u     IPv4 0x98beca42cd0067e3      0t0                 TCP 192.168.0.19:57746->18.154.101.73:https (SYN_SENT)
lychee  5619 goldbaum   43u     IPv4 0xf80b0cecc593e983      0t0                 TCP 192.168.0.19:57753->151.101.0.223:https (ESTABLISHED)
lychee  5619 goldbaum   44u     IPv4 0x89465f37679d04e6      0t0                 TCP 192.168.0.19:57691->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   45u     IPv4 0xdaf6e0822936b577      0t0                 TCP 192.168.0.19:57611->18.154.101.73:https (SYN_SENT)
lychee  5619 goldbaum   46u     IPv4 0xa685a099fe295fa7      0t0                 TCP 192.168.0.19:57656->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   47u     IPv4 0xbfe13f1462ec926b      0t0                 TCP 192.168.0.19:57640->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   48u     IPv4 0xdafbff3f51e844c3      0t0                 TCP 192.168.0.19:57657->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   49u     IPv4 0x37ec3d4796e2232e      0t0                 TCP 192.168.0.19:57739->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   50u     IPv4 0xac517c6b440116e4      0t0                 TCP 192.168.0.19:57625->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   51u     IPv4 0x22d016f844ac0707      0t0                 TCP 192.168.0.19:57763->140.82.113.4:https (SYN_SENT)
lychee  5619 goldbaum   52u     IPv4 0xec6fa5d8cd3fbb7a      0t0                 TCP 192.168.0.19:57663->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   53u     IPv4  0xa3ce098ccef8d2c      0t0                 TCP 192.168.0.19:57522->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   54u     IPv4 0xc7888ec2605e979c      0t0                 TCP 192.168.0.19:57641->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   55u     IPv4 0xd70cfbc7e9f74268      0t0                 TCP 192.168.0.19:57721->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   56u     IPv4 0xc4d6b46bbb4a4857      0t0                 TCP 192.168.0.19:57749->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   57u     IPv4 0xb947caa22c0cd91b      0t0                 TCP 192.168.0.19:57709->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   58u     IPv4 0x31f2fde5e7f4d7ab      0t0                 TCP 192.168.0.19:57737->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   59u     IPv4 0x2cf9ce18e1569219      0t0                 TCP 192.168.0.19:57743->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   60u     IPv4 0xc8eab58fbe9558fd      0t0                 TCP 192.168.0.19:57806->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum   61u     IPv4 0x158603b58bb12462      0t0                 TCP 192.168.0.19:57564->18.154.101.73:https (SYN_SENT)
lychee  5619 goldbaum   62u     IPv4 0xc4139082112551a2      0t0                 TCP 192.168.0.19:57828->151.101.0.223:https (SYN_SENT)
lychee  5619 goldbaum   63u     IPv4 0xbc1bdb7bd54e46fb      0t0                 TCP 192.168.0.19:57638->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   64u   KQUEUE                                                 count=0, state=0xa
lychee  5619 goldbaum   65u     IPv4 0xe001e56091520857      0t0                 TCP 192.168.0.19:57740->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   66u     IPv4 0xb3bedd6e184b7b04      0t0                 TCP 192.168.0.19:57565->18.154.101.73:https (SYN_SENT)
lychee  5619 goldbaum   67u    systm 0xc7a870432ac8520c      0t0                     [ctl com.apple.netsrc id 7 unit 9]
lychee  5619 goldbaum   68u     IPv4 0x56d6ed14fef087e1      0t0                 TCP 192.168.0.19:57802->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum   69u     IPv4 0xfbc845a584bf9e99      0t0                 TCP 192.168.0.19:57575->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum   70u   KQUEUE                                                 count=0, state=0xa
lychee  5619 goldbaum   71u     IPv4 0x8a0c1e82959b0911      0t0                 TCP 192.168.0.19:57421->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   72u     IPv4  0x1849cfcf548f7c7      0t0                 TCP 192.168.0.19:57745->18.154.101.73:https (SYN_SENT)
lychee  5619 goldbaum   73u     IPv4 0x2d9820b60cb2398b      0t0                 TCP 192.168.0.19:57761->151.101.0.223:https (ESTABLISHED)
lychee  5619 goldbaum   74u     IPv4 0xcef62980592b0e02      0t0                 TCP 192.168.0.19:57750->140.82.113.4:https (ESTABLISHED)
lychee  5619 goldbaum   75u   KQUEUE                                                 count=0, state=0x8
lychee  5619 goldbaum   76u     IPv4 0x8dc578f9ce284538      0t0                 TCP 192.168.0.19:57803->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum   77u     IPv4 0x76f74d0bba297187      0t0                 TCP 192.168.0.19:57705->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   78u     IPv4 0x4bd4bd64ab238014      0t0                 TCP 192.168.0.19:57572->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   79u     IPv4 0x9a4600baf3573fd9      0t0                 TCP 192.168.0.19:57560->18.154.101.73:https (SYN_SENT)
lychee  5619 goldbaum   80u     IPv4 0xbfd70a6669ec9807      0t0                 TCP 192.168.0.19:57594->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   81u     IPv4 0xe7677d34f99d5898      0t0                 TCP 192.168.0.19:57462->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   82u     IPv4 0x30e542490aaa0978      0t0                 TCP 192.168.0.19:57551->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   83u     IPv4 0x14220e61e6158ce7      0t0                 TCP 192.168.0.19:57461->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   84u     IPv4 0x5c67a38a76675163      0t0                 TCP 192.168.0.19:57799->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   85u     IPv4 0xd96e96e4c974295e      0t0                 TCP 192.168.0.19:57757->151.101.0.223:https (ESTABLISHED)
lychee  5619 goldbaum   86u     IPv4 0xa9c1b7b767dd1e49      0t0                 TCP 192.168.0.19:57833->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum   87u     IPv4   0x51ad1f4c2257ee      0t0                 TCP 192.168.0.19:57829->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum   88u     IPv4 0x659021a480e74967      0t0                 TCP 192.168.0.19:57556->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   89u     IPv4 0x8e932b637cd21764      0t0                 TCP 192.168.0.19:57649->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   90u     IPv4 0xf104d4aaf8f05fb1      0t0                 TCP 192.168.0.19:57651->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   91u     IPv4  0xcd7454a48ce7b28      0t0                 TCP 192.168.0.19:57680->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   92u     IPv4 0xbb10c721fb572cc0      0t0                 TCP 192.168.0.19:57755->151.101.0.223:https (SYN_SENT)
lychee  5619 goldbaum   93u     IPv4 0x4367019c02d0f004      0t0                 TCP 192.168.0.19:57487->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   94u     IPv4 0x24b6efe42c333d24      0t0                 TCP 192.168.0.19:57759->151.101.0.223:https (ESTABLISHED)
lychee  5619 goldbaum   95u     IPv4 0x37d0c9e15561b20c      0t0                 TCP 192.168.0.19:57668->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum   96u   KQUEUE                                                 count=0, state=0xa
lychee  5619 goldbaum   97u     IPv4 0x143efabba1979d16      0t0                 TCP 192.168.0.19:57762->151.101.0.223:https (ESTABLISHED)
lychee  5619 goldbaum   98u     IPv4 0xce5c8719bc25ab94      0t0                 TCP 192.168.0.19:57658->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum   99u     IPv4 0x350c38caa6a652a3      0t0                 TCP 192.168.0.19:57736->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  100u   KQUEUE                                                 count=0, state=0x8
lychee  5619 goldbaum  101u     IPv4 0xb7798bb0d6a18168      0t0                 TCP 192.168.0.19:57758->151.101.0.223:https (SYN_SENT)
lychee  5619 goldbaum  102r      DIR               1,18     3648           117346766 /Users/goldbaum/Documents/pyo3/target/doc/pyo3/types
lychee  5619 goldbaum  103u     IPv4 0xef7127f8fdc88f54      0t0                 TCP 192.168.0.19:57730->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  104u     IPv4 0xd69f1f6d4fa04aa1      0t0                 TCP 192.168.0.19:57496->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  105u     IPv4 0x6a6b70906ca1c099      0t0                 TCP 192.168.0.19:57626->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  106u     IPv4 0x188f01d55ddc6df9      0t0                 TCP 192.168.0.19:57756->140.82.113.4:https (ESTABLISHED)
lychee  5619 goldbaum  107u     IPv4  0x133bfb93ebcc3a9      0t0                 TCP 192.168.0.19:57808->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  108u     IPv4 0x782dcefb02cd907b      0t0                 TCP 192.168.0.19:57780->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  109u     IPv4  0xa6da9180d2193e2      0t0                 TCP 192.168.0.19:57571->18.154.101.73:https (SYN_SENT)
lychee  5619 goldbaum  110u   KQUEUE                                                 count=0, state=0x8
lychee  5619 goldbaum  111u     IPv4  0xdc481d189e0826d      0t0                 TCP 192.168.0.19:57782->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  112u     IPv4 0xd8e4abc062ddb52a      0t0                 TCP 192.168.0.19:57781->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  113u     IPv4 0x56082efb1b40543d      0t0                 TCP 192.168.0.19:57718->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  114u     IPv4 0xc98a243ba3a075ce      0t0                 TCP 192.168.0.19:57773->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  115u     IPv4 0x43db7b0288ae2207      0t0                 TCP 192.168.0.19:57558->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  116u     IPv4 0x6e45bc1acf830134      0t0                 TCP 192.168.0.19:57720->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  117u     IPv4 0xb33ff9db5771b510      0t0                 TCP 192.168.0.19:57772->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  118u     IPv4 0xca5580ad3e52c86f      0t0                 TCP 192.168.0.19:57648->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  119u     IPv4 0xbb6fcf6d51bff78e      0t0                 TCP 192.168.0.19:57815->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  120u     IPv4 0xd799c1a8e828a1af      0t0                 TCP 192.168.0.19:57614->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  121u     IPv4 0xa7fdf398314e938d      0t0                 TCP 192.168.0.19:57674->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  122u     IPv4 0x4e8ae12442d2ee88      0t0                 TCP 192.168.0.19:57574->18.154.101.73:https (SYN_SENT)
lychee  5619 goldbaum  123u     IPv4 0x2cacb034310740b0      0t0                 TCP 192.168.0.19:57777->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  124u     IPv4 0xc2275c9d58966f70      0t0                 TCP 192.168.0.19:57444->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  125u     IPv4 0x7f0f4806d43572c6      0t0                 TCP 192.168.0.19:57834->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  126u     IPv4 0x9c4663c4e4711361      0t0                 TCP 192.168.0.19:57733->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  127u     IPv4 0xad9745622b285753      0t0                 TCP 192.168.0.19:57652->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  128u     IPv4 0x2eb2f6f8e3fdd3cc      0t0                 TCP 192.168.0.19:57785->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  129u   KQUEUE                                                 count=0, state=0x8
lychee  5619 goldbaum  130u     IPv4 0x99cfe3790a48d8e2      0t0                 TCP 192.168.0.19:57734->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  131u     IPv4 0x185a589365ffbf6a      0t0                 TCP 192.168.0.19:57591->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  132u     IPv4 0xf7b5828cc88830ff      0t0                 TCP 192.168.0.19:57650->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  133u     IPv4 0xfd97d1034d122d56      0t0                 TCP 192.168.0.19:57724->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  134u     IPv4 0xbef05cb2bbb6a44f      0t0                 TCP 192.168.0.19:57812->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  135u     IPv4 0x134993515e7fb0ff      0t0                 TCP 192.168.0.19:57783->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  136u     IPv4 0x77c0f9fc1eee044f      0t0                 TCP 192.168.0.19:57784->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  137u     IPv4 0x5681816368ae7a16      0t0                 TCP 192.168.0.19:57476->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  138u     IPv4 0xaf4704d8ee881ef2      0t0                 TCP 192.168.0.19:57695->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  139u     IPv4 0x243048c2641ddb83      0t0                 TCP 192.168.0.19:57505->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  140u     IPv4 0xb3d2b4b15ca03502      0t0                 TCP 192.168.0.19:57477->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  141u     IPv4 0x916fcb7efa0f3c8a      0t0                 TCP 192.168.0.19:57824->151.101.0.223:https (SYN_SENT)
lychee  5619 goldbaum  142u   KQUEUE                                                 count=0, state=0x8
lychee  5619 goldbaum  143u     IPv4 0xd5a2a989d892a843      0t0                 TCP 192.168.0.19:57766->140.82.113.4:https (SYN_SENT)
lychee  5619 goldbaum  144u     IPv4 0x2cd1874366398e0b      0t0                 TCP 192.168.0.19:57779->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  145u     IPv4 0x529252c7ddf932c7      0t0                 TCP 192.168.0.19:57696->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  146u     IPv4 0x9ec12f59c256247c      0t0                 TCP 192.168.0.19:57786->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  147u     IPv4 0xf92be82bafe6be83      0t0                 TCP 192.168.0.19:57787->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  148u   KQUEUE                                                 count=0, state=0x8
lychee  5619 goldbaum  149u     IPv4 0xf962532e19238c4d      0t0                 TCP 192.168.0.19:57805->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  150u     IPv4 0xa7847d2af7243d32      0t0                 TCP 192.168.0.19:57554->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  151u     IPv4  0x879119e0e28be0a      0t0                 TCP 192.168.0.19:57561->18.154.101.73:https (SYN_SENT)
lychee  5619 goldbaum  152u     IPv4 0xefa1e985bb7dbf2f      0t0                 TCP 192.168.0.19:57788->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  153u     IPv4 0xb542a2a6d3452397      0t0                 TCP 192.168.0.19:57771->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  154u     IPv4 0x23a3edfc701c05ca      0t0                 TCP 192.168.0.19:57550->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  155u     IPv4 0x3183a1e021bd4b5f      0t0                 TCP 192.168.0.19:57827->151.101.0.223:https (SYN_SENT)
lychee  5619 goldbaum  156u     IPv4  0x793a6bfb3ed1fb6      0t0                 TCP 192.168.0.19:57557->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  157u     IPv4 0x37b1f3d08cbebdb1      0t0                 TCP 192.168.0.19:57563->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  158u     IPv4 0x595babcfa55badce      0t0                 TCP 192.168.0.19:57559->18.154.101.73:https (SYN_SENT)
lychee  5619 goldbaum  159u     IPv4 0x8b8ced1b73097e66      0t0                 TCP 192.168.0.19:57798->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  160u     IPv4 0xb66e067e9924f5e2      0t0                 TCP 192.168.0.19:57555->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  161u     IPv4 0x144775543667c1ca      0t0                 TCP 192.168.0.19:57791->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  162u     IPv4 0x84536ec7f445f84d      0t0                 TCP 192.168.0.19:57583->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  163u     IPv4 0xdc6e8dc4487ed651      0t0                 TCP 192.168.0.19:57581->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  164u     IPv4 0xea664e6eaba52e61      0t0                 TCP 192.168.0.19:57587->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  165u     IPv4 0x4cfcaa092e02b34d      0t0                 TCP 192.168.0.19:57769->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  166u     IPv4 0x33d6670e6c25dc50      0t0                 TCP 192.168.0.19:57770->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  167u     IPv4 0xed1669727f50d7d1      0t0                 TCP 192.168.0.19:57584->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  168u     IPv4 0xca6abaa7a3d994c5      0t0                 TCP 192.168.0.19:57795->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  169u     IPv4 0xe1d00a9fb43d59d8      0t0                 TCP 192.168.0.19:57819->151.101.0.223:https (SYN_SENT)
lychee  5619 goldbaum  170u     IPv4 0x961d7b82054a990c      0t0                 TCP 192.168.0.19:57796->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  171u     IPv4 0x7bcbd25a4ee81120      0t0                 TCP 192.168.0.19:57600->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  172u     IPv4 0x35735915ab930c9f      0t0                 TCP 192.168.0.19:57778->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  173u     IPv4 0x672fb79e0305c709      0t0                 TCP 192.168.0.19:57596->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  174u     IPv4 0xe993ab0607e0420a      0t0                 TCP 192.168.0.19:57597->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  175u     IPv4 0xb9f739b7bbaef518      0t0                 TCP 192.168.0.19:57789->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  176u   KQUEUE                                                 count=0, state=0xa
lychee  5619 goldbaum  177u     IPv4  0x9a2aee19afdc6ff      0t0                 TCP 192.168.0.19:57790->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  178u     IPv4 0x25c3355e466ec18e      0t0                 TCP 192.168.0.19:57794->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  179u     IPv4 0x9a8f952f6fe5b00a      0t0                 TCP 192.168.0.19:57605->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  180u     IPv4 0xd151c0179c81f065      0t0                 TCP 192.168.0.19:57768->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  181u     IPv4 0xf6e366054b0f090b      0t0                 TCP 192.168.0.19:57607->18.154.101.73:https (SYN_SENT)
lychee  5619 goldbaum  182u     IPv4 0x903b6a32bda5f7ab      0t0                 TCP 192.168.0.19:57774->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  183u     IPv4 0x66731193dcd41cf9      0t0                 TCP 192.168.0.19:57792->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  184u     IPv4 0x648d7e181637478d      0t0                 TCP 192.168.0.19:57610->18.154.101.73:https (SYN_SENT)
lychee  5619 goldbaum  185u     IPv4 0x6d5b87bbaedcef15      0t0                 TCP 192.168.0.19:57793->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  186u     IPv4 0x2fd9e11dac65e8fe      0t0                 TCP 192.168.0.19:57804->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  187u     IPv4 0xb1341167778a1ac8      0t0                 TCP 192.168.0.19:57775->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  188u     IPv4 0x712083a0aaa5269b      0t0                 TCP 192.168.0.19:57767->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  189u     IPv4 0x7be4fff815ef5c07      0t0                 TCP 192.168.0.19:57825->151.101.0.223:https (SYN_SENT)
lychee  5619 goldbaum  190u     IPv4 0x4598ac8f6e797bcd      0t0                 TCP 192.168.0.19:57836->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  191u     IPv4 0xa9d19269109ce7f2      0t0                 TCP 192.168.0.19:57776->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  192u     IPv4 0x423dd8d101bdb973      0t0                 TCP 192.168.0.19:57624->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  193u     IPv4 0xcd59a74d5b596dab      0t0                 TCP 192.168.0.19:57800->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  194u     IPv4 0x1449ed7c1720364e      0t0                 TCP 192.168.0.19:57807->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  195u     IPv4 0x63e989de9dc7c49c      0t0                 TCP 192.168.0.19:57628->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  196u     IPv4 0x8e662ee82d924a05      0t0                 TCP 192.168.0.19:57632->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  197u     IPv4  0x3480efcbd53c8b2      0t0                 TCP 192.168.0.19:57635->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  198u     IPv4 0x29c9d41a7a8af48e      0t0                 TCP 192.168.0.19:57633->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  199u     IPv4 0xc89b57e1ee56883e      0t0                 TCP 192.168.0.19:57647->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  200u     IPv4 0x9bafb64a74f40904      0t0                 TCP 192.168.0.19:57801->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  201u     IPv4 0x1cf7595911a551bc      0t0                 TCP 192.168.0.19:57639->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  202u     IPv4 0x86a09865e4f38216      0t0                 TCP 192.168.0.19:57643->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  203u     IPv4 0x88cd7d61cfd2cc2a      0t0                 TCP 192.168.0.19:57645->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  204u     IPv4 0xaf49713193192a71      0t0                 TCP 192.168.0.19:57843->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  205u     IPv4 0x6b60ab60a54bcfd8      0t0                 TCP 192.168.0.19:57809->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  206u     IPv4 0x361fe18d3320abcd      0t0                 TCP 192.168.0.19:57810->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  207u     IPv4 0xcc149e0b74635dc5      0t0                 TCP 192.168.0.19:57669->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  208u     IPv4 0xfae544c075f710c4      0t0                 TCP 192.168.0.19:57814->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  209u     IPv4 0xb2dcaecf07f43011      0t0                 TCP 192.168.0.19:57842->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  210u     IPv4 0x90ace2ffeb934f2c      0t0                 TCP 192.168.0.19:57678->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  211u     IPv4 0xc59bf997d943277f      0t0                 TCP 192.168.0.19:57681->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  212u     IPv4 0x6f9733048bf990dd      0t0                 TCP 192.168.0.19:57686->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  213u     IPv4 0x17d5837906590ef7      0t0                 TCP 192.168.0.19:57685->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  214u     IPv4 0x29c5b306c1a59ce4      0t0                 TCP 192.168.0.19:57841->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  215u     IPv4 0x3a1a5ff0139a53aa      0t0                 TCP 192.168.0.19:57830->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  216u     IPv4 0xf4509ba62bcc3b56      0t0                 TCP 192.168.0.19:57687->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  217u     IPv4 0x43b392d841f5eb53      0t0                 TCP 192.168.0.19:57688->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  218u     IPv4 0x5ff4c1ec47e6dedf      0t0                 TCP 192.168.0.19:57690->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  219u     IPv4 0x938a699dd62d90b9      0t0                 TCP 192.168.0.19:57692->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  220u     IPv4 0x52692444d47532d0      0t0                 TCP 192.168.0.19:57811->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  221u     IPv4 0xdbc3b912f6e45a4c      0t0                 TCP 192.168.0.19:57697->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  222u     IPv4 0x203e8b9e6861f87b      0t0                 TCP 192.168.0.19:57694->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  223u     IPv4 0x13d4c0f7185e8c7d      0t0                 TCP 192.168.0.19:57698->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  224u     IPv4 0x29327e47d33431b5      0t0                 TCP 192.168.0.19:57706->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  225u     IPv4 0x91429d5da40ab2db      0t0                 TCP 192.168.0.19:57816->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  226u     IPv4  0x704e83de8dbe101      0t0                 TCP 192.168.0.19:57702->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  227u     IPv4 0x6711e34259613f7e      0t0                 TCP 192.168.0.19:57821->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  228u     IPv4 0x2f89a78285b2af60      0t0                 TCP 192.168.0.19:57703->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  229u     IPv4 0x161255d9543fcc27      0t0                 TCP 192.168.0.19:57707->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  230u     IPv4 0x21127b1173740562      0t0                 TCP 192.168.0.19:57710->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  231u     IPv4 0x3b2811e3bb0bebd5      0t0                 TCP 192.168.0.19:57708->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  232u     IPv4 0x3bb1be6fd6412140      0t0                 TCP 192.168.0.19:57711->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  233u     IPv4 0xdd7fea372d8ade9c      0t0                 TCP 192.168.0.19:57712->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  234u     IPv4 0x97fc3da1f9019d72      0t0                 TCP 192.168.0.19:57817->151.101.0.223:https (SYN_SENT)
lychee  5619 goldbaum  235u     IPv4 0x992bfaffabbdf1ba      0t0                 TCP 192.168.0.19:57714->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  236u     IPv4 0x5d716868a82a131c      0t0                 TCP 192.168.0.19:57716->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  237u     IPv4 0x7e4bd38c197fd125      0t0                 TCP 192.168.0.19:57717->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  238u   KQUEUE                                                 count=0, state=0x8
lychee  5619 goldbaum  239u     IPv4 0x6db4e72982e35675      0t0                 TCP 192.168.0.19:57722->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  240u     IPv4 0xf72533f8eb42ab24      0t0                 TCP 192.168.0.19:57838->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  241u     IPv4 0x13266a97235544a0      0t0                 TCP 192.168.0.19:57726->18.154.101.73:https (ESTABLISHED)
lychee  5619 goldbaum  242u     IPv4 0xe6b0c4d4da9c3c5e      0t0                 TCP 192.168.0.19:57728->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  243u     IPv4 0x5fe02c47c4a0a552      0t0                 TCP 192.168.0.19:57731->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  244u     IPv4 0x3f110a4f3dd4e1eb      0t0                 TCP 192.168.0.19:57738->18.154.101.111:https (ESTABLISHED)
lychee  5619 goldbaum  245u     IPv4 0x4f232aed1752a06b      0t0                 TCP 192.168.0.19:57820->151.101.0.223:https (SYN_SENT)
lychee  5619 goldbaum  246u     IPv4 0xeb53479ee39cc5b0      0t0                 TCP 192.168.0.19:57822->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  247u     IPv4 0xbdf40d039868ce05      0t0                 TCP 192.168.0.19:57818->151.101.0.223:https (SYN_SENT)
lychee  5619 goldbaum  248u     IPv4 0x831a2b8ae1537878      0t0                 TCP 192.168.0.19:57831->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  249u     IPv4 0x1ac69637592f3bcb      0t0                 TCP 192.168.0.19:57823->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  250u     IPv4 0xb5729d6ef3051f3c      0t0                 TCP 192.168.0.19:57826->151.101.0.223:https (SYN_SENT)
lychee  5619 goldbaum  251u     IPv4 0x4cbde9455e767b3b      0t0                 TCP 192.168.0.19:57832->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  252u     IPv4 0x14fd049deeceb29c      0t0                 TCP 192.168.0.19:57837->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  253u     IPv4  0xee4b6975504cb6d      0t0                 TCP 192.168.0.19:57839->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  254u     IPv4 0xba5a8ce46e6153d5      0t0                 TCP 192.168.0.19:57835->18.154.101.111:https (SYN_SENT)
lychee  5619 goldbaum  255u     IPv4 0x1b0ad9f75a73dbc7      0t0                 TCP 192.168.0.19:57844->18.154.101.111:https (SYN_SENT)
```

When I run with `RUST_BACKTRACE=1`, I also sometimes see this backtrace printed:

```
Error: Cannot read input content from file `/Users/goldbaum/Documents/pyo3/target/doc/pyo3/types/struct.PyWeakrefProxy.html`

Caused by:
    Too many open files (os error 24)

Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   2: lychee::run::{{closure}}
   3: tokio::runtime::park::CachedParkThread::block_on
   4: lychee::main
   5: std::sys::backtrace::__rust_begin_short_backtrace
   6: std::rt::lang_start::{{closure}}
   7: std::rt::lang_start_internal
   8: _main
```

**Comment by mre** [comment]
Note: https://crates.io/crates/limits-rs

**Comment by mre** [comment]
We did some work along those lines recently and the issue should be resolved. If anyone has the bandwidth, please check out the latest `master` branch and try again. We'd be thankful for feedback and can reopen the issue if problems persist. :)
