### ISSUE TITLE
include_mail and exclude_mail flags do not work from config file

### ISSUE THREAD

**Issue by sohailekline** [lycheeverse/lychee#1354]
If we pass `include_mail` or `exclude_mail` flags to command in terminal they work as expected. However, if we pass any of these flag in config file (lychee.toml) they do not work. Other configuration are working from config file.

Lychee version = 0.14.1

### lychee.toml

```
exclude_path = [ './node_modules/*' ]
include_mail = true
```

### output
```
{
  "total": 2,
  "successful": 0,
  "unknown": 0,
  "unsupported": 0,
  "timeouts": 0,
  "redirects": 0,
  "excludes": 1,
  "errors": 1,
  "cached": 0,
  "success_map": {},
  "fail_map": {
    "/Users/.../src/lychee/__tests__/integration/index-spec.md": [
      {
        "url": "https://testingabc.io/",
        "status": {
          "text": "Failed: Network error"
        }
      }
    ]
  },
  "suggestion_map": {},
  "excluded_map": {
    "/Users/.../src/lychee/__tests__/integration/index-spec.md": [
      {
        "url": "mailto:hello-test@testingabc.io",
        "status": {
          "text": "Excluded"
        }
      }
    ]
  },
  "duration_secs": 0,
  "detailed_stats": true
}
```
### Actual:
It is still excluding the emails.

### Expected:
It should have checked the email as well and returned that in failed_map.

**Comment by mre** [comment]
Sorry, that was on oversight on how we merge the commandline flags with the config file. Should be resolved with #1357.

**Comment by sohailekline** [comment]
@mre Thank you. 
When can we expect it be released? At the moment, I am still seeing 0.14.1 as latest version.

**Comment by sohailekline** [comment]
That would be so great. I will wait for `0.14.2` release. 
Thanks
