### ISSUE TITLE
Reference style links are checked or reported multiple times

### ISSUE THREAD

**Issue by theofidry** [lycheeverse/lychee#1660]
Taken from this job: https://github.com/box-project/box/actions/runs/13615816913/job/38058706641

And an excerpt in case the job output is removed later:

```
✔ [200] https://secure.php.net/manual/en/phar.setsignaturealgorithm.php
✔ [200] https://secure.php.net/manual/en/book.zlib.php
✔ [200] https://symfony.com/slack-invite
✔ [200] https://symfony.com/slack-invite
## Summary

| Status        | Count |
|---------------|-------|
| 🔍 Total      | 644   |
| ✅ Successful | 642   |
| ⏳ Timeouts   | 0     |
| 🔀 Redirected | 0     |
| 👻 Excluded   | 0     |
| ❓ Unknown    | 0     |
| 🚫 Errors     | 2     |

## Errors per input

### Errors in doc/docker.md

* [404] [https://docs.docker.com/samples/library/php/](https://docs.docker.com/samples/library/php/) | Failed: Network error: Not Found

### Errors in ./doc/docker.md

* [404] [https://docs.docker.com/samples/library/php/](https://docs.docker.com/samples/library/php/) | Failed: Network error: Not Found
*
```

You can see the 404 appears twice. The underlying code was something like this:

```md
blablabla [`docker-php-ext-install`][docker-php-ext-install] blablabla [`docker-php-ext-install`][docker-php-ext-install]

[docker-php-ext-install]: https://deadlink.com
```

In other words I am using a reference-style link in my document and it looks like it is either checked or reported for every usage, rather than once.

**Comment by thomas-zahner** [comment]
The implementation should probably make use of some sort of HashSet that keeps track of all paths that previously were [canonicalized](https://doc.rust-lang.org/std/fs/fn.canonicalize.html). This should make it possible to remove duplicates from the file checking process, so that a file that was provided via `README.md` and via `./docs/../README.md` is checked only once.

**Comment by tooomm** [comment]
Is this fully addressed with [#1781](https://github.com/lycheeverse/lychee/pull/1781)?

**Comment by mre** [comment]
Yeah, should be. Thanks for the heads-up. Closing.

**Comment by thomas-zahner** [comment]
@tooomm Thanks for the contribution. Yes, I think the problem reported in this issue is solved. I also mentioned [canonicalizing](https://doc.rust-lang.org/std/fs/fn.canonicalize.html) file inputs.

> This should make it possible to remove duplicates from the file checking process, so that a file that was provided via README.md and via ./docs/../README.md is checked only once.

But thinking about it I realise that this should not be necessary. Other tools such as ripgrep also don't do this, so we can forget about that part.

**Comment by tooomm** [comment]
Running the most recent version, I still see a lot of duplicates:
https://github.com/Cockatrice/cockatrice.github.io/actions/runs/17156704956/job/48675191268#step:3:72

**Comment by mre** [comment]
@tooomm can you create a new issue for that?
