### ISSUE TITLE
lychee shows network error: forbidden for valid links

### ISSUE THREAD

**Issue by Rizwan-Hasan** [lycheeverse/lychee#733]
Suddenly lychee shows this error for valid links. These links are valid and accessible from the browser too.

```
❯ lychee --max-concurrency 1 --no-progress --verbose "work/ok.txt"
✗ [403] https://catboost.ai/ | Network error: Forbidden
✗ [403] https://catboost.ai/en/docs/concepts/python-reference_datasets_msrank | Network error: Forbidden

Issues found in 1 input. Find details below.

[work/ok.txt]:
✗ [403] https://catboost.ai/ | Network error: Forbidden
✗ [403] https://catboost.ai/en/docs/concepts/python-reference_datasets_msrank | Network error: Forbidden

🔍 2 Total ✅ 0 OK 🚫 2 Errors (HTTP:2)
```

**Comment by mre** [comment]
Hum, looks like it's an issue on your end. 🤔 At least it works over here:

```
❯❯❯ lychee --max-concurrency 1 --no-progress --verbose "work/ok.txt"
✔ [200] https://catboost.ai/
✔ [200] https://catboost.ai/en/docs/concepts/python-reference_datasets_msrank

🔍 2 Total ✅ 2 OK 🚫 0 Errors
```

Can you try from a different network? Or maybe reconnect to your wifi? Maybe it also was just a temporary hickup?

**Comment by Rizwan-Hasan** [comment]
Hi @mre ,

It originally happened on github action. Then I tried it on my local pc and still same.
Here's the github action log [https://github.com/Rizwan-Hasan/clearml-docs/runs/7825833483?check_suite_focus=true](https://github.com/Rizwan-Hasan/clearml-docs/runs/7825833483?check_suite_focus=true)

**Comment by mre** [comment]
Oh I see. No clue what's going on there yet.

**Comment by Rizwan-Hasan** [comment]
Any idea how to make it work?

**Comment by Rizwan-Hasan** [comment]
I just tried it on a cloud server and same error.

**Comment by mre** [comment]
What's strange is that it works for me. So it must be something that's wrong with the client-side.
Some thoughts:

* Did you try a different user-agent?
* Has any configuration been changed for catboost.ai recently? A firewall rule or a server config for example?
* If the catboost.ai docs aren't self-hosted, maybe your hosting provider changed a setting.
* Can you check the catboost.ai logs if you have access?
* When was the last time it worked? Was it a permanent error from then on or did it occasionally work for a while?

I'm afraid there ain't much I can do on my end other than asking questions. 😅

**Comment by Rizwan-Hasan** [comment]
On your thoughts,
 - Tried with a different user-agent (used the same user-agent my browser has) and the error continues.
 - We don't have any access to catboost.ai as it's not ours. So, can't tell if anything has changed there.
 - I've just checked one GitHub Action log of 2 months ago and the error on these two links was there too.

**Comment by Rizwan-Hasan** [comment]
I've created a new git repository to make a mock test. And the result is negative.
Repository: [https://github.com/Rizwan-Hasan/test-lychee-links](https://github.com/Rizwan-Hasan/test-lychee-links)
Logs: [https://github.com/Rizwan-Hasan/test-lychee-links/runs/7826437363](https://github.com/Rizwan-Hasan/test-lychee-links/runs/7826437363?check_suite_focus=true)

**Comment by Rizwan-Hasan** [comment]
Hi @mre ,

Any update?

**Comment by mre** [comment]
Nope, no update. I don't think I can help much here. 🙁 It works over here, so it's definitely a problem with the server preventing certain clients from getting access. It's not something we can fix in lychee.

**Comment by Rizwan-Hasan** [comment]
Understood. But it's not working on my local PC and Linode server also. I'm confused.

**Comment by mre** [comment]
Yeah that's definitely weird. If anyone can help out narrow this down, please run the following command on your machine and report back the result.

```sh
echo 'https://catboost.ai' | lychee -
```

**Comment by Rizwan-Hasan** [comment]
```
❯ echo 'https://catboost.ai' | lychee -
Issues found in 1 input. Find details below.

[stdin]:
✗ [403] https://catboost.ai/ | Network error: Forbidden

🔍 1 Total ✅ 0 OK 🚫 1 Error (HTTP:1)
```
```
❯ curl -I 'https://catboost.ai'        
HTTP/1.1 200 OK
Content-Length: 79368
Content-Security-Policy: default-src 'none'; script-src 'unsafe-eval' 'unsafe-inline' 'nonce-EzZqyXy1OG/i2ADhnTKeSw==' mc.yandex.ru social.yandex.ru yastatic.net; style-src 'unsafe-inline' mc.yandex.ru yastatic.net; img-src 'self' data: avatars.yandex.net avatars.mds.yandex.net avatars.mdst.yandex.net mc.yandex.ru ext.captcha.yandex.net yastatic.net; connect-src 'self' mc.yandex.ru; frame-src www.youtube.com video.yandex.ru player.video.yandex.net; media-src ext.captcha.yandex.net; font-src yastatic.net; report-uri https://csp.yandex.net/csp?from=promo-catboost-2017&yandex_login=undefined&yandexuid=undefined;
Content-Type: text/html; charset=utf-8
Date: Tue, 16 Aug 2022 09:35:03 GMT
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```

**Comment by mre** [comment]
Does this work for you?

```sh
 echo 'https://catboost.ai' | lychee --user-agent 'curl/7.79.1' -
```

**Comment by Rizwan-Hasan** [comment]
Not working
```
❯  echo 'https://catboost.ai' | lychee --user-agent 'curl/7.79.1' -
Issues found in 1 input. Find details below.

[stdin]:
✗ [403] https://catboost.ai/ | Network error: Forbidden

🔍 1 Total ✅ 0 OK 🚫 1 Error (HTTP:1)
```

**Comment by mre** [comment]
No clue, really. The last thing that comes to mind is 
```
echo 'https://catboost.ai' | lychee --user-agent 'curl/7.79.1' --headers 'Accept=*/*' --
```

That's the only thing I can see when I inspect the curl command.
You can compare which headers curl is sending in your case with ```curl -v https://catboost.ai```.

**Comment by Rizwan-Hasan** [comment]
```
❯ echo 'https://catboost.ai' | lychee --headers 'Accept=*/*' --user-agent 'curl/7.79.1' -
Issues found in 1 input. Find details below.

[stdin]:
✗ [403] https://catboost.ai/ | Network error: Forbidden

🔍 1 Total ✅ 0 OK 🚫 1 Error (HTTP:1)
```

**Comment by mre** [comment]
@lebensterben could you run a test on your side if you find the time?

**Comment by lebensterben** [comment]
@mre 

```
𝛌> echo 'https://catboost.ai' | ./target/debug/lychee --user-agent 'curl/7.79.1' --headers 'Accept=*/*' -
Issues found in 1 input. Find details below.

[stdin]:
✗ [403] https://catboost.ai/ | Failed: Network error: Forbidden
```

**Comment by lebensterben** [comment]
This issue is similar to https://github.com/lycheeverse/lychee/issues/715

We need to build a minimal curl-like client with reqwest to check whether the problem is in reqwest or lychee.

**Comment by mre** [comment]
The strange thing is that it works for me with lychee. 🤔 

I sort of hacked together a curl/reqwest client here: https://github.com/lycheeverse/geturl-test
Can you folks test again?

```sh
# reqwest (the default)
~/C/s/r/geturl ❯❯❯ cargo run -- 'https://catboost.ai'
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/geturl 'https://catboost.ai'`
200 OK

# libcurl
~/C/s/r/geturl ❯❯❯ cargo run --features curl -- 'https://catboost.ai'
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/geturl 'https://catboost.ai'`
200 OK
~/C/s/r/geturl ❯❯❯ 
```

**Comment by lebensterben** [comment]
```
𝛌> cargo run -- 'https://catboost.ai'
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/geturl 'https://catboost.ai'`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: unexpected HTTP response code 403 Forbidden for URL https://catboost.ai', src/bin/geturl.rs:9:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by lebensterben** [comment]
We may need this

https://github.com/4JX/reqwest-impersonate

**Comment by mre** [comment]
I've added support for it to [getcurl-test](https://github.com/lycheeverse/geturl-test) and it indeed works:

```
> cargo run --no-default-features --features curl -- 'https://catboost.ai'
get_url: https://catboost.ai
response: Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("catboost.ai")), port: None, path: "/", query: None, fragment: None }, status: 200, headers: {"content-length": "79366", "content-security-policy": "default-src 'none'; script-src 'unsafe-eval' 'unsafe-inline' 'nonce-06bmt7YDganaJlR0CEne6Q==' mc.yandex.ru social.yandex.ru yastatic.net; style-src 'unsafe-inline' mc.yandex.ru yastatic.net; img-src 'self' data: avatars.yandex.net avatars.mds.yandex.net avatars.mdst.yandex.net mc.yandex.ru ext.captcha.yandex.net yastatic.net; connect-src 'self' mc.yandex.ru; frame-src www.youtube.com video.yandex.ru player.video.yandex.net; media-src ext.captcha.yandex.net; font-src yastatic.net; report-uri https://csp.yandex.net/csp?from=promo-catboost-2017&yandex_login=undefined&yandexuid=undefined;", "content-type": "text/html; charset=utf-8", "date": "Sun, 23 Oct 2022 23:21:38 GMT", "x-content-type-options": "nosniff", "x-frame-options": "DENY", "x-xss-protection": "1; mode=block"} }
status: 200 OK
```

Tested locally and inside a Github codespace. Can you both test it on your machines as well?
Just clone the project and run the command above.

If it works I really don't know if we should add `reqwest-impersonate` to the project. Might be a maintenance issue down the road as it could diverge from `reqwest` and is maintained by a single (yet awesome) person.

**Comment by lebensterben** [comment]
I won't be able to test it for a while because I get covid (again).

**Comment by mre** [comment]
Get well soon. 🤗

**Comment by mre** [comment]
@Rizwan-Hasan in case you find the time, maybe you can test this: https://github.com/lycheeverse/lychee/issues/733#issuecomment-1288228473

**Comment by Rizwan-Hasan** [comment]
@mre Hi

I pulled a docker image `docker pull rust`, pulled the repository [geturl-test](https://github.com/lycheeverse/geturl-test) then ran `cargo run -- 'https://catboost.ai'` as the readme suggests. Here's the log

```bash
root@22c7cf489de3:/geturl-test# cargo run -- 'https://catboost.ai'
    Updating git repository `https://github.com/4JX/h2.git`
    Updating git repository `https://github.com/4JX/hyper.git`
    Updating crates.io index
    Updating git repository `https://github.com/4JX/reqwest-impersonate.git`
    Updating git repository `https://github.com/4JX/boring`
    Updating git submodule `https://github.com/google/boringssl.git`
    Updating git submodule `https://github.com/google/boringssl.git`
  Downloaded bitflags v1.3.2
  Downloaded memchr v2.5.0
  Downloaded quote v1.0.21
  Downloaded mio v0.8.4
  Downloaded serde_urlencoded v0.7.1
  Downloaded reqwest v0.11.12
  Downloaded syn v1.0.103
  Downloaded unicode-ident v1.0.5
  Downloaded ipnet v2.5.0
  Downloaded hyper-tls v0.5.0
  Downloaded httparse v1.8.0
  Downloaded http-body v0.4.5
  Downloaded foreign-types-shared v0.1.1
  Downloaded foreign-types v0.3.2
  Downloaded tower-service v0.3.2
  Downloaded tokio-util v0.7.4
  Downloaded openssl v0.10.42
  Downloaded tokio-native-tls v0.3.0
  Downloaded tracing v0.1.37
  Downloaded fnv v1.0.7
  Downloaded num_cpus v1.13.1
  Downloaded pin-utils v0.1.0
  Downloaded native-tls v0.2.10
  Downloaded tracing-core v0.1.30
  Downloaded want v0.3.0
  Downloaded try-lock v0.2.3
  Downloaded bytes v1.2.1
  Downloaded log v0.4.17
  Downloaded pin-project-lite v0.2.9
  Downloaded indexmap v1.9.1
  Downloaded once_cell v1.15.0
  Downloaded url v2.3.1
  Downloaded slab v0.4.7
  Downloaded form_urlencoded v1.1.0
  Downloaded ryu v1.0.11
  Downloaded httpdate v1.0.2
  Downloaded itoa v1.0.4
  Downloaded unicode-bidi v0.3.8
  Downloaded mime v0.3.16
  Downloaded percent-encoding v2.2.0
  Downloaded tinyvec_macros v0.1.0
  Downloaded serde v1.0.147
  Downloaded http v0.2.8
  Downloaded tinyvec v1.6.0
  Downloaded proc-macro2 v1.0.47
  Downloaded openssl-macros v0.1.0
  Downloaded anyhow v1.0.66
  Downloaded base64 v0.13.1
  Downloaded autocfg v1.1.0
  Downloaded cfg-if v1.0.0
  Downloaded cc v1.0.73
  Downloaded futures-core v0.3.25
  Downloaded idna v0.3.0
  Downloaded futures-task v0.3.25
  Downloaded futures-sink v0.3.25
  Downloaded futures-io v0.3.25
  Downloaded pkg-config v0.3.25
  Downloaded openssl-probe v0.1.5
  Downloaded futures-channel v0.3.25
  Downloaded futures-util v0.3.25
  Downloaded socket2 v0.4.7
  Downloaded openssl-sys v0.9.77
  Downloaded hashbrown v0.12.3
  Downloaded unicode-normalization v0.1.22
  Downloaded tokio v1.21.2
  Downloaded libc v0.2.135
  Downloaded encoding_rs v0.8.31
  Downloaded 67 crates (5.6 MB) in 2.05s (largest was `encoding_rs` at 1.4 MB)
   Compiling autocfg v1.1.0
   Compiling libc v0.2.135
   Compiling cfg-if v1.0.0
   Compiling log v0.4.17
   Compiling proc-macro2 v1.0.47
   Compiling pin-project-lite v0.2.9
   Compiling cc v1.0.73
   Compiling once_cell v1.15.0
   Compiling memchr v2.5.0
   Compiling pkg-config v0.3.25
   Compiling quote v1.0.21
   Compiling futures-core v0.3.25
   Compiling bytes v1.2.1
   Compiling unicode-ident v1.0.5
   Compiling syn v1.0.103
   Compiling futures-task v0.3.25
   Compiling itoa v1.0.4
   Compiling openssl v0.10.42
   Compiling fnv v1.0.7
   Compiling foreign-types-shared v0.1.1
   Compiling futures-util v0.3.25
   Compiling futures-io v0.3.25
   Compiling native-tls v0.2.10
   Compiling pin-utils v0.1.0
   Compiling tinyvec_macros v0.1.0
   Compiling httparse v1.8.0
   Compiling futures-channel v0.3.25
   Compiling hashbrown v0.12.3
   Compiling bitflags v1.3.2
   Compiling futures-sink v0.3.25
   Compiling percent-encoding v2.2.0
   Compiling openssl-probe v0.1.5
   Compiling try-lock v0.2.3
   Compiling serde v1.0.147
   Compiling encoding_rs v0.8.31
   Compiling httpdate v1.0.2
   Compiling tower-service v0.3.2
   Compiling unicode-bidi v0.3.8
   Compiling ryu v1.0.11
   Compiling anyhow v1.0.66
   Compiling mime v0.3.16
   Compiling ipnet v2.5.0
   Compiling base64 v0.13.1
   Compiling tracing-core v0.1.30
   Compiling tokio v1.21.2
   Compiling slab v0.4.7
   Compiling indexmap v1.9.1
   Compiling http v0.2.8
   Compiling foreign-types v0.3.2
   Compiling tinyvec v1.6.0
   Compiling openssl-sys v0.9.77
   Compiling form_urlencoded v1.1.0
   Compiling tracing v0.1.37
   Compiling want v0.3.0
   Compiling http-body v0.4.5
   Compiling unicode-normalization v0.1.22
   Compiling num_cpus v1.13.1
   Compiling mio v0.8.4
   Compiling socket2 v0.4.7
   Compiling idna v0.3.0
   Compiling url v2.3.1
   Compiling serde_urlencoded v0.7.1
   Compiling tokio-util v0.7.4
   Compiling h2 v0.3.14 (https://github.com/4JX/h2.git?branch=imp#90af7b9d)
   Compiling openssl-macros v0.1.0
   Compiling hyper v0.14.18 (https://github.com/4JX/hyper.git?branch=v0.14.18-patched#abf28d87)
   Compiling tokio-native-tls v0.3.0
   Compiling hyper-tls v0.5.0
   Compiling reqwest v0.11.12
   Compiling tectonic_geturl v0.0.0-dev.0 (/geturl-test)
warning: variable does not need to be mutable
 --> src/bin/geturl.rs:9:13
  |
9 |         let mut response = backend.get_url(&url, &mut status).unwrap();
  |             ----^^^^^^^^
  |             |
  |             help: remove this `mut`
  |
  = note: `#[warn(unused_mut)]` on by default

warning: `tectonic_geturl` (bin "geturl") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 2m 59s
     Running `target/debug/geturl 'https://catboost.ai'`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: unexpected HTTP response code 403 Forbidden for URL https://catboost.ai', src/bin/geturl.rs:9:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
root@22c7cf489de3:/geturl-test# 
```

**Comment by mre** [comment]
Okay thanks. The second one should not have failed. It's an error on my end. However I do expect it to fail just like the first test with request.
At least the results have always been consistent between them on my end.

For the last one, which is the most promising one. You need to install boringssl for that first.

**Comment by mre** [comment]
...and for boringssl you need to install `cmake` first. https://cmake.org/install/

**Comment by Rizwan-Hasan** [comment]
I had to install `cmake` and `clang` both to work. Here's the log
```bash
root@e4e91d5d237d:/geturl-test# cargo run --no-default-features --features reqwest_impersonate -- 'https://catboost.ai'
warning: unused variable: `redirect_policy`
  --> src/reqwest_impersonate.rs:59:13
   |
59 |         let redirect_policy = Policy::custom(move |attempt| {
   |             ^^^^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_redirect_policy`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: `tectonic_geturl` (lib) generated 1 warning
warning: variable does not need to be mutable
 --> src/bin/geturl.rs:9:13
  |
9 |         let mut response = backend.get_url(&url, &mut status).unwrap();
  |             ----^^^^^^^^
  |             |
  |             help: remove this `mut`
  |
  = note: `#[warn(unused_mut)]` on by default

warning: `tectonic_geturl` (bin "geturl") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/geturl 'https://catboost.ai'`
get_url: https://catboost.ai
response: Response { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("catboost.ai")), port: None, path: "/", query: None, fragment: None }, status: 200, headers: {"content-length": "79367", "content-security-policy": "default-src 'none'; script-src 'unsafe-eval' 'unsafe-inline' 'nonce-/lIFeLdebbwR139V24X0Xg==' mc.yandex.ru social.yandex.ru yastatic.net; style-src 'unsafe-inline' mc.yandex.ru yastatic.net; img-src 'self' data: avatars.yandex.net avatars.mds.yandex.net avatars.mdst.yandex.net mc.yandex.ru ext.captcha.yandex.net yastatic.net; connect-src 'self' mc.yandex.ru; frame-src www.youtube.com video.yandex.ru player.video.yandex.net; media-src ext.captcha.yandex.net; font-src yastatic.net; report-uri https://csp.yandex.net/csp?from=promo-catboost-2017&yandex_login=undefined&yandexuid=undefined;", "content-type": "text/html; charset=utf-8", "date": "Fri, 28 Oct 2022 19:51:08 GMT", "x-content-type-options": "nosniff", "x-frame-options": "DENY", "x-xss-protection": "1; mode=block"} }
status: 200 OK
root@e4e91d5d237d:/geturl-test# 
```

**Comment by mre** [comment]
Dang. It works. 😞 

That means if we integrate that backend into lychee it would solve your issue.
Two questions (@lebensterben)

* do we want to do this?
* why did it work on my machine before (with the normal backend)?

**Comment by lebensterben** [comment]
@mre 

I don't know the answer for the second question.

For the first one, I suggest to test it on other related issue where browsers are able to open a URL but curl and lychee are not.

- If those similar issues can be fixed also, then definitely it worth integrating it despite the cost of additional dependency.

**Comment by mre** [comment]
Good idea. Did some tests but haven't found other use-cases yet where this fixes the problem. I'll keep this on hold until then.

**Comment by mre** [comment]
Similar case that got resolved with browser impersonation:
https://github.com/lycheeverse/lychee/discussions/819

Thinking about adding reqwest-impersonate as a fallback to handle such cases.

**Comment by Rizwan-Hasan** [comment]
Hi @mre,

Is there any update about the issue? We're still facing it. 😥

**Comment by mre** [comment]
No updates, but if I find the time I will create a pull request to integrate reqwest impersonate as a fallback backend. It will be an optional library feature, but it will be enabled by default in the binary.
It's a great match because I want to refactor the client code anyway soon.
Thanks for the reminder.

**Comment by Rizwan-Hasan** [comment]
That's great. Looking forward to the release then.

**Comment by mre** [comment]
Bad news. I wanted to integrate this, but I don't think it's possible right now.
`reqwest-impersonate` patches some dependencies (e.g. hyper) and therefore cannot be published on crates.io. If we integrate it into lychee, that means we couldn't publish the library on crates.io either even if we put `reqwest-impersonate` behind a feature flag, which is disabled by default.
See https://github.com/rust-lang/cargo/issues/6738.
Is there a possibility that I don't see right now?

**Comment by mre** [comment]
As much as I would like this to be part of lychee, I don't think there is an easy solution right now.
Unless the upstream crate can get published on crates.io we don't stand a chance at integrating it.
I've created an upstream issue at https://github.com/4JX/reqwest-impersonate/issues/2.
